### ISSUE TITLE
Exclude Zone

### ISSUE THREAD

**Issue by shahbour** [spencergibb/spring-cloud-eureka-zone-affinity-sample#2]
Is their a way to ignore zone or define list of accepted zone , for example if we have 3 zones ( office, shahbour, joe ) 

i want the services in zone shahbour to only talk to shahbour primary and office as secondary and ignore all other zones.

I tried it as below and it is working if a service exist on same zone but if their is no service on same zone it do load balance on all the others 

```
spring:
  profiles: shahbour
eureka:
  instance:
    metadataMap:
      zone: shahbour
  client:
    preferSameZoneEureka: true
    shahbour: http://office:8761/eureka/
    availabilityZones:
      lebanon: shahbour,office
```
This is for development environment where i am trying to setup each developer to use his machine as a zone and if service does not exist use office server as backup but don't use other developers .
